### ISSUE TITLE
design with git notes

### ISSUE THREAD

**Issue by DavidCarl** [prolike/timereg#13]
Flere issues, et for hver user storie i [dilly dally](http://code.praqma.com/dilly-dally/)

**Comment by DavidCarl** [comment]
Vi har kigget lidt på format som det skal gemmes i (metadata) og git notes ser ud til at være local og personlige.

**Comment by Alfen321** [comment]
`git notes add -m "msg" <object>`  adds a message to the object with the default being HEAD but can only be used if there is no comments on the current object, but can overwrite current notes with `-f`

`git notes append -m "msg" <object>` like `git notes add` but adds the comment as new line. Can also be used as the first comment and therefore `git notes add` wouldn't be useful in our case.

It is possible to add more than one comment with multiple `-m` like `git notes append -m "msg 1" -m "msg 2" <object>`
You can also use `-F` or `--file` instead of `-m` it will take the content of the file as a standard input to the message

To push the content of note use `git push origin refs/notes/commits`
To fetch notes use `git fetch origin refs/notes/commits:refs/notes/commits`

**Comment by Alfen321** [comment]
Git objects are stored in the folder `.git/objects` and are split up in sub folders, the first two characters of the hash-name is the folder it is stored in.To get a list of all objects use `find .git/objects type -f`
To get the type of git object use `git cat-file -t <hash-name>` the -t is for type.
To get the content of the git object use `git cat-file -p <hash-name>` the -p is for prettify.
Notes are stored in a blob object (git object)
The file `.git/refs/notes/commits` contains a string of characters which is the name of a commit object (git object)
A commit object contains 4 values a reference to a tree object, parent (the commit before this), author (git configs user.name, user.email and a timestamp), and committer (git configs user.name, user.email and a timestamp).
A git tree contains a reference/hash-name of a blob and a hash-name of the code commit the notes are added to.

Git notes have a auto-merge feature but does not work in most cases e.g. conflicts with the .git/refs/notes/commits, conflicts in the history

In order to fix a merge conflict we need to store the local state and get the remote state downloaded. To do this we can rename our own .git/refs/notes/commits and use a `git fetch origin refs/notes/commits` and look around in the git objects.

**Comment by DavidCarl** [comment]
Closed in reference to #76 Made our own system compared to git notes
